---
title: "Introduction to R"
subtitle: "2022 ENAR Fostering Diversity in Biostatistics Workshop"
output: "github_document"
---

This workshop is designed for high school and undergraduate students who are new to R and it is presented as part of the "2022 ENAR Fostering Diversity in Biostatistics Workshop".

`r emo::ji("spiral_calendar")` March 27, 2022  
`r emo::ji("three_o_clock")` 3pm - 4:30pm ET  
`r emo::ji("pushpin")` Zoom (see email for info)  

<br>

## Agenda

- ### Welcome + data collection (click [here](https://forms.gle/tJHjPdDM5EusB3Fm6) for survey)
- ### Activity 1: [TikTok lyrics](https://minecr.shinyapps.io/tiktok_lyrics/)
- ### Activity 2: [All about you!](https://minecr.shinyapps.io/all_about_you/)

<br>

## Instructors

#### [Dr. Maria Tackett](https://www.mariatackett.net/)

I am an Assistant Professor of the Practice in the Department of Statistical Science at Duke University. My research focuses on using technology and active learning techniques to enhance student learning and motivation in large undergraduate statistics courses. Prior to joining the faculty at Duke, I earned a Ph.D. in Statistics from the University of Virginia, where my research focused on using a Bayesian approach to quantify uncertainty in forensic science techniques, with an emphasis on latent fingerprint evidence.

#### [Dr. Allison Theobold](https://statistics.calpoly.edu/allison-theobold)

I am an Assistant Professor of Statistics at Cal Poly in beautiful San Luis
Obispo, California. I received my doctorate in Statistics, with an emphasis
in Statistics Education, from Montana State University.My work focuses on
innovation in statistics and data science education, with an emphasis on
equitable pedagogy and learning trajectories. I am also interested in
exploring pedagogical approaches which build student authority in the
classroom and enhance the retention of under-represented students in STEM.
Being a part of the statistics education community is very important to me. 
I am a committee member of the ASA’s Section on Statistics and Data Science
Education Mentoring Program, and co-organizer of Preparing to Teach
(https://preparingtoteach.org/), a day-long workshop preparing early career
faculty to teach courses in statistics and data science. 



